In [1]:
from pathlib import Path
import pandas as pd
import numpy as np

project_dir = Path(r"C:\Multimodal_KIRC_Project")
rnaseq_dir = project_dir / "01_raw_downloads" / "RNAseq"

sample_sheet_path = rnaseq_dir / "gdc_sample_sheet.2026-08-07.tsv"

sample_sheet = pd.read_csv(sample_sheet_path, sep="\t")

print("RNA-seq sample sheet loaded successfully.")
print("Rows:", len(sample_sheet))
print("Columns:", sample_sheet.shape[1])
print("Unique cases:", sample_sheet["Case ID"].nunique())

display(sample_sheet.head())

RNA-seq sample sheet loaded successfully.
Rows: 542
Columns: 11
Unique cases: 533

,File ID,File Name,Data Category,Data Type,Project ID,Case ID,Sample ID,Tissue Type,Tumor Descriptor,Specimen Type,Preservation Method
0,44c858ac-1ce0-491a-aef5-979224aa09f5,144cc9bb-bd29-4986-89a7-5855168dac8e.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-B8-4146,TCGA-B8-4146-01B,Tumor,Primary,Unknown,Unknown
1,3bca5269-8bb3-4826-bc22-e7b068853f45,44dce722-f50f-4b75-bcf4-aac9afd39e41.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-BP-4977,TCGA-BP-4977-01A,Tumor,Primary,Unknown,Unknown
2,b65b4ebc-e8b9-4926-8761-56b99fbd9e9a,19f6bda2-39bb-4733-8efc-a4626afb6bd1.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-BP-4981,TCGA-BP-4981-01A,Tumor,Primary,Unknown,Unknown
3,2faa29c8-49e9-4fda-baea-f73583f3a27f,11c9e0b9-c94c-466f-877a-65325a76dcaf.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-CJ-5675,TCGA-CJ-5675-01A,Tumor,Primary,Unknown,Unknown
4,633fef2c-c9ce-4b76-ae7b-0dfcc4123a6f,ba0e046d-ea06-4a64-9847-14b35eb72aee.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-B0-4845,TCGA-B0-4845-01A,Tumor,Primary,Unknown,Unknown

In [2]:
case_counts = sample_sheet["Case ID"].value_counts()

duplicate_cases = case_counts[case_counts > 1]

print("Total RNA-seq files:", len(sample_sheet))
print("Unique patients:", sample_sheet["Case ID"].nunique())
print("Patients with multiple RNA-seq files:", len(duplicate_cases))
print("Extra files beyond one per patient:", len(sample_sheet) - sample_sheet["Case ID"].nunique())

display(
    duplicate_cases
    .rename("number_of_files")
    .reset_index()
    .rename(columns={"index": "Case ID"})
)

Total RNA-seq files: 542
Unique patients: 533
Patients with multiple RNA-seq files: 5
Extra files beyond one per patient: 9

        Case ID  number_of_files
0  TCGA-B2-5633                3
1  TCGA-B2-5635                3
2  TCGA-B2-3923                3
3  TCGA-B2-3924                3
4  TCGA-DV-A4W0                2

In [3]:
duplicate_profiles = (
    sample_sheet[
        sample_sheet["Case ID"].isin(duplicate_cases.index)
    ]
    .sort_values(["Case ID", "Sample ID", "File ID"])
)

display(
    duplicate_profiles[
        [
            "Case ID",
            "Sample ID",
            "File ID",
            "File Name",
            "Tissue Type",
            "Tumor Descriptor",
            "Specimen Type"
        ]
    ]
)

,Case ID,Sample ID,File ID,File Name,Tissue Type,Tumor Descriptor,Specimen Type
480,TCGA-B2-3923,TCGA-B2-3923-01A,2b393323-81e3-49e2-9acd-18eb8ab0c563,d96fc441-a213-4f24-b2b1-a23d63883532.rna_seq.a...,Tumor,Primary,Unknown
96,TCGA-B2-3923,TCGA-B2-3923-01A,4134fa64-6365-4a43-b990-48342be44405,2a0d7ffd-21a2-4c9f-b420-9f78e9b8689b.rna_seq.a...,Tumor,Primary,Unknown
97,TCGA-B2-3923,TCGA-B2-3923-01B,d514c3bc-c1e1-4028-9822-90ad703a3a8d,d5340889-fb1c-411d-922c-a9f69e1ac405.rna_seq.a...,Tumor,Primary,Unknown
386,TCGA-B2-3924,TCGA-B2-3924-01A,056c67e7-03b3-40cc-8c19-d6938ad634aa,343ac8e1-8afa-4e36-a373-ca28c3e7a713.rna_seq.a...,Tumor,Primary,Unknown
500,TCGA-B2-3924,TCGA-B2-3924-01A,df630d23-f007-4cc4-9910-edb44046d556,a40c1d70-1750-45d0-a85b-688331b029ea.rna_seq.a...,Tumor,Primary,Unknown
388,TCGA-B2-3924,TCGA-B2-3924-01B,3324e6df-28f9-42d8-8465-0fcc2d618004,f08c47f7-7b61-46a2-a961-d5fced8ebde5.rna_seq.a...,Tumor,Primary,Unknown
43,TCGA-B2-5633,TCGA-B2-5633-01A,61894bd0-9fdb-4bb1-b32c-f52dbc10c850,1e28caa3-197f-4deb-95c1-f6d8a41756ca.rna_seq.a...,Tumor,Primary,Unknown
84,TCGA-B2-5633,TCGA-B2-5633-01A,bdb74506-8766-42e1-922e-e03da4637a70,dc6421de-439b-4764-87bf-c1922cfeba3c.rna_seq.a...,Tumor,Primary,Unknown
446,TCGA-B2-5633,TCGA-B2-5633-01B,307fc027-0530-452b-8fa9-d46f7fc73d0e,9cc9f5b7-bbbb-4d3b-8d98-9bf4425a214b.rna_seq.a...,Tumor,Primary,Unknown
74,TCGA-B2-5635,TCGA-B2-5635-01A,b98e59fc-120a-45c4-aade-3b59ca4a1a86,c276c214-acd9-44b3-b932-971c77c4fa91.rna_seq.a...,Tumor,Primary,Unknown
73,TCGA-B2-5635,TCGA-B2-5635-01A,ebd01ba8-06cd-417a-b41d-05379e430fd2,82a0446c-baf9-4d27-bc14-73e00dc729ab.rna_seq.a...,Tumor,Primary,Unknown
313,TCGA-B2-5635,TCGA-B2-5635-01B,2afa2c24-7bbf-4855-acb8-feaa22dc4c33,27ea00ff-5f53-4110-9e56-8674a8e0ae40.rna_seq.a...,Tumor,Primary,Unknown
324,TCGA-DV-A4W0,TCGA-DV-A4W0-01A,07b09d0e-fac2-42a7-9cac-ac1e38a92298,e7da171a-02e6-4369-a961-885bc2f7e0ba.rna_seq.a...,Tumor,Primary,Unknown
86,TCGA-DV-A4W0,TCGA-DV-A4W0-05A,f8ba326c-a068-4d8c-a544-07fd13c39cbd,b79c9932-bc2b-4c87-b954-3b6efd0d76e5.rna_seq.a...,Tumor,New Primary,Unknown

In [4]:
sample_counts = (
    sample_sheet
    .groupby(["Case ID", "Sample ID"])
    .size()
    .reset_index(name="n_files")
)

same_sample_duplicates = sample_counts[
    sample_counts["n_files"] > 1
]

display(same_sample_duplicates)

          Case ID         Sample ID  n_files
186  TCGA-B2-3923  TCGA-B2-3923-01A        2
188  TCGA-B2-3924  TCGA-B2-3924-01A        2
194  TCGA-B2-5633  TCGA-B2-5633-01A        2
196  TCGA-B2-5635  TCGA-B2-5635-01A        2

In [5]:
from pathlib import Path
import pandas as pd
import numpy as np

data_dir = Path(r"C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\data")

same_sample_profiles = sample_sheet.merge(
    same_sample_duplicates[["Case ID", "Sample ID"]],
    on=["Case ID", "Sample ID"],
    how="inner"
)

display(
    same_sample_profiles[
        ["Case ID", "Sample ID", "File ID", "File Name"]
    ].sort_values(["Case ID", "Sample ID", "File ID"])
)

,Case ID,Sample ID,File ID,File Name
6,TCGA-B2-3923,TCGA-B2-3923-01A,2b393323-81e3-49e2-9acd-18eb8ab0c563,d96fc441-a213-4f24-b2b1-a23d63883532.rna_seq.a...
4,TCGA-B2-3923,TCGA-B2-3923-01A,4134fa64-6365-4a43-b990-48342be44405,2a0d7ffd-21a2-4c9f-b420-9f78e9b8689b.rna_seq.a...
5,TCGA-B2-3924,TCGA-B2-3924-01A,056c67e7-03b3-40cc-8c19-d6938ad634aa,343ac8e1-8afa-4e36-a373-ca28c3e7a713.rna_seq.a...
7,TCGA-B2-3924,TCGA-B2-3924-01A,df630d23-f007-4cc4-9910-edb44046d556,a40c1d70-1750-45d0-a85b-688331b029ea.rna_seq.a...
0,TCGA-B2-5633,TCGA-B2-5633-01A,61894bd0-9fdb-4bb1-b32c-f52dbc10c850,1e28caa3-197f-4deb-95c1-f6d8a41756ca.rna_seq.a...
3,TCGA-B2-5633,TCGA-B2-5633-01A,bdb74506-8766-42e1-922e-e03da4637a70,dc6421de-439b-4764-87bf-c1922cfeba3c.rna_seq.a...
2,TCGA-B2-5635,TCGA-B2-5635-01A,b98e59fc-120a-45c4-aade-3b59ca4a1a86,c276c214-acd9-44b3-b932-971c77c4fa91.rna_seq.a...
1,TCGA-B2-5635,TCGA-B2-5635-01A,ebd01ba8-06cd-417a-b41d-05379e430fd2,82a0446c-baf9-4d27-bc14-73e00dc729ab.rna_seq.a...

In [6]:
def find_expression_file(file_id, file_name):
    matches = list(data_dir.rglob(file_name))
    
    if len(matches) == 0:
        raise FileNotFoundError(
            f"Could not find {file_name} for File ID {file_id}"
        )
    
    if len(matches) > 1:
        print(f"Warning: multiple matches found for {file_name}")
    
    return matches[0]


def read_star_counts(file_path):
    df = pd.read_csv(
        file_path,
        sep="\t",
        comment="#"
    )
    
    return df

In [8]:
def find_expression_file(file_id, file_name):
    matches = list(data_dir.rglob(file_name))
    
    if len(matches) == 0:
        raise FileNotFoundError(
            f"Could not find {file_name} for File ID {file_id}"
        )
    
    if len(matches) > 1:
        print(f"Warning: multiple matches found for {file_name}")
    
    return matches[0]


def read_star_counts(file_path):
    df = pd.read_csv(
        file_path,
        sep="\t",
        comment="#"
    )
    
    return df

In [10]:
data_dir = Path(r"C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq")

In [11]:
all_tsv = list(data_dir.rglob("*.tsv"))

print("TSV files found:", len(all_tsv))

for p in all_tsv[:10]:
    print(p)

TSV files found: 543
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\gdc_sample_sheet.2026-08-07.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\000d81dd-9ba4-4852-9090-2bf22f6483f0\09755ce8-ed89-411a-a42f-b3edc4e41eeb.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\00174492-1adc-4310-8147-a622befbb466\84e40c7e-2f60-4461-b14c-0859697295a4.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\00ddbdd1-f29d-438b-820b-aacb111a3ec4\e635dbc7-ef8d-45e2-acd2-b961f0c8b600.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\017de1fe-6f36-4324-a20a-9d9ee3439d8f\1b366431-2a13-45a5-a21e-931d473de6d4.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\02669516-0c84-46b4-9ff1-ab147ff1ddcc\5adfce9d-f650-4dd3-8382-28e475427cd1.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\02f13d48-a03a-42e8-917d-e5d9025e2898\c56a5910-5ae3-434a-9093-a4b264a644fd.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\03c6d5d2-1a33-4ae7-9421-f43b14fc97bd\d03c971c-8baa-46bc-8b0a-1ff8b29a8f75.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\040bcb51-b1dd-4666-819f-3ffed0b5ebb0\4ef51bd6-d020-4a5f-9142-9d8349308146.rna_seq.augmented_star_gene_counts.tsv
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\040e6555-b1a3-43ca-ae2b-a972fc01fa19\975ca807-d276-43f7-95e6-4b04bf2409c8.rna_seq.augmented_star_gene_counts.tsv

In [12]:
test_row = same_sample_profiles.iloc[0]

test_path = find_expression_file(
    test_row["File ID"],
    test_row["File Name"]
)

print("Located file:")
print(test_path)

Located file:
C:\Multimodal_KIRC_Project\01_raw_downloads\RNAseq\61894bd0-9fdb-4bb1-b32c-f52dbc10c850\1e28caa3-197f-4deb-95c1-f6d8a41756ca.rna_seq.augmented_star_gene_counts.tsv

In [13]:
test_df = read_star_counts(test_path)

print("Shape:", test_df.shape)
print("Columns:")
print(test_df.columns.tolist())

display(test_df.head(10))

Shape: (60664, 9)
Columns:
['gene_id', 'gene_name', 'gene_type', 'unstranded', 'stranded_first', 'stranded_second', 'tpm_unstranded', 'fpkm_unstranded', 'fpkm_uq_unstranded']

,gene_id,gene_name,gene_type,unstranded,stranded_first,stranded_second,tpm_unstranded,fpkm_unstranded,fpkm_uq_unstranded
0,N_unmapped,NaN,NaN,7324866,7324866,7324866,NaN,NaN,NaN
1,N_multimapping,NaN,NaN,3306574,3306574,3306574,NaN,NaN,NaN
2,N_noFeature,NaN,NaN,2264497,25100483,25234967,NaN,NaN,NaN
3,N_ambiguous,NaN,NaN,4570958,1073882,1067600,NaN,NaN,NaN
4,ENSG00000000003.15,TSPAN6,protein_coding,2461,1225,1237,49.8081,12.6773,12.3147
5,ENSG00000000005.6,TNMD,protein_coding,6,2,4,0.3732,0.0950,0.0923
6,ENSG00000000419.13,DPM1,protein_coding,933,485,448,70.9637,18.0618,17.5453
7,ENSG00000000457.14,SCYL3,protein_coding,528,390,364,7.0424,1.7924,1.7412
8,ENSG00000000460.17,C1orf112,protein_coding,164,206,222,2.5219,0.6419,0.6235
9,ENSG00000000938.13,FGR,protein_coding,703,337,366,19.0829,4.8570,4.7181

In [14]:
def extract_gene_tpm(file_path):
    df = pd.read_csv(
        file_path,
        sep="\t",
        comment="#"
    )

    # Keep actual gene rows only
    df = df[df["gene_id"].astype(str).str.startswith("ENSG")].copy()

    # Keep gene identifier and TPM
    df = df[["gene_id", "gene_name", "tpm_unstranded"]].copy()

    return df

In [15]:
comparison_results = []

for (case_id, sample_id), group in same_sample_profiles.groupby(
    ["Case ID", "Sample ID"]
):

    if len(group) != 2:
        continue

    row1 = group.iloc[0]
    row2 = group.iloc[1]

    path1 = find_expression_file(
        row1["File ID"],
        row1["File Name"]
    )

    path2 = find_expression_file(
        row2["File ID"],
        row2["File Name"]
    )

    df1 = extract_gene_tpm(path1)
    df2 = extract_gene_tpm(path2)

    merged = df1.merge(
        df2,
        on="gene_id",
        suffixes=("_file1", "_file2")
    )

    pearson_r = merged[
        ["tpm_unstranded_file1", "tpm_unstranded_file2"]
    ].corr(method="pearson").iloc[0, 1]

    spearman_r = merged[
        ["tpm_unstranded_file1", "tpm_unstranded_file2"]
    ].corr(method="spearman").iloc[0, 1]

    mean_abs_difference = np.mean(
        np.abs(
            merged["tpm_unstranded_file1"]
            - merged["tpm_unstranded_file2"]
        )
    )

    comparison_results.append(
        {
            "Case ID": case_id,
            "Sample ID": sample_id,
            "File 1": row1["File ID"],
            "File 2": row2["File ID"],
            "Genes compared": len(merged),
            "Pearson r": pearson_r,
            "Spearman rho": spearman_r,
            "Mean absolute TPM difference": mean_abs_difference
        }
    )

duplicate_expression_comparison = pd.DataFrame(
    comparison_results
)

display(duplicate_expression_comparison)

,Case ID,Sample ID,File 1,File 2,Genes compared,Pearson r,Spearman rho,Mean absolute TPM difference
0,TCGA-B2-3923,TCGA-B2-3923-01A,4134fa64-6365-4a43-b990-48342be44405,2b393323-81e3-49e2-9acd-18eb8ab0c563,60660,0.019043,0.767990,18.692652
1,TCGA-B2-3924,TCGA-B2-3924-01A,056c67e7-03b3-40cc-8c19-d6938ad634aa,df630d23-f007-4cc4-9910-edb44046d556,60660,0.049081,0.807115,20.473910
2,TCGA-B2-5633,TCGA-B2-5633-01A,61894bd0-9fdb-4bb1-b32c-f52dbc10c850,bdb74506-8766-42e1-922e-e03da4637a70,60660,0.025956,0.813730,18.550874
3,TCGA-B2-5635,TCGA-B2-5635-01A,ebd01ba8-06cd-417a-b41d-05379e430fd2,b98e59fc-120a-45c4-aade-3b59ca4a1a86,60660,0.023063,0.827366,17.577402

In [16]:
log_comparison_results = []

for (case_id, sample_id), group in same_sample_profiles.groupby(
    ["Case ID", "Sample ID"]
):

    if len(group) != 2:
        continue

    row1 = group.iloc[0]
    row2 = group.iloc[1]

    path1 = find_expression_file(
        row1["File ID"],
        row1["File Name"]
    )

    path2 = find_expression_file(
        row2["File ID"],
        row2["File Name"]
    )

    df1 = extract_gene_tpm(path1)
    df2 = extract_gene_tpm(path2)

    merged = df1.merge(
        df2,
        on="gene_id",
        suffixes=("_file1", "_file2")
    )

    x = np.log2(merged["tpm_unstranded_file1"] + 1)
    y = np.log2(merged["tpm_unstranded_file2"] + 1)

    pearson_log = x.corr(y, method="pearson")
    spearman_log = x.corr(y, method="spearman")

    median_abs_log_difference = np.median(
        np.abs(x - y)
    )

    log_comparison_results.append(
        {
            "Case ID": case_id,
            "Sample ID": sample_id,
            "Genes compared": len(merged),
            "Log2(TPM+1) Pearson r": pearson_log,
            "Log2(TPM+1) Spearman rho": spearman_log,
            "Median absolute log2 difference":
                median_abs_log_difference
        }
    )

log_duplicate_comparison = pd.DataFrame(
    log_comparison_results
)

display(log_duplicate_comparison)

,Case ID,Sample ID,Genes compared,Log2(TPM+1) Pearson r,Log2(TPM+1) Spearman rho,Median absolute log2 difference
0,TCGA-B2-3923,TCGA-B2-3923-01A,60660,0.919858,0.767990,0.123846
1,TCGA-B2-3924,TCGA-B2-3924-01A,60660,0.922113,0.807115,0.124901
2,TCGA-B2-5633,TCGA-B2-5633-01A,60660,0.903452,0.813730,0.113687
3,TCGA-B2-5635,TCGA-B2-5635-01A,60660,0.923211,0.827366,0.110898

In [17]:
import json

metadata_path = (
    rnaseq_dir
    / "metadata.repository.2026-08-07.json"
)

with open(metadata_path, "r", encoding="utf-8") as f:
    metadata = json.load(f)

print(type(metadata))
print("Number of metadata records:", len(metadata))

<class 'list'>
Number of metadata records: 542

In [18]:
print(metadata[0].keys())

dict_keys(['data_format', 'access', 'associated_entities', 'file_name', 'submitter_id', 'data_category', 'analysis', 'platform', 'file_size', 'md5sum', 'file_id', 'data_type', 'state', 'experimental_strategy'])

In [19]:
from pprint import pprint
pprint(metadata[0])

{'access': 'open',
 'analysis': {'analysis_id': 'c304e15b-cfbd-400f-881a-45f582c88a47',
              'created_datetime': '2021-12-13T19:00:47.992559-06:00',
              'input_files': [{'access': 'controlled',
                               'average_base_quality': 38,
                               'average_insert_size': 969,
                               'average_read_length': 50,
                               'created_datetime': '2021-12-13T17:59:36.019908-06:00',
                               'data_category': 'Sequencing Reads',
                               'data_format': 'BAM',
                               'data_type': 'Aligned Reads',
                               'experimental_strategy': 'RNA-Seq',
                               'file_id': '90df4ec5-31a1-4360-b24e-9b5dbe5f56e4',
                               'file_name': '144cc9bb-bd29-4986-89a7-5855168dac8e.rna_seq.genomic.gdc_realn.bam',
                               'file_size': 5597227825,
                               'md5sum': '82ac93531e3e363dafe0782f79bb1285',
                               'pairs_on_diff_chr': 254876,
                               'platform': 'Illumina',
                               'proportion_base_mismatch': 0.002437107,
                               'proportion_reads_duplicated': 0,
                               'proportion_reads_mapped': 0.9862605786849248,
                               'state': 'released',
                               'submitter_id': '242ac3e7-06fe-42ec-ba99-e9c653eba9cd',
                               'total_reads': 128680456,
                               'updated_datetime': '2023-07-12T10:44:04.997120-05:00',
                               'wgs_coverage': 'Not Applicable'}],
              'state': 'released',
              'submitter_id': '144cc9bb-bd29-4986-89a7-5855168dac8e_star__counts',
              'updated_datetime': '2022-01-19T12:49:49.189936-06:00',
              'workflow_link': 'https://github.com/NCI-GDC/gdc-rnaseq-cwl/blob/5d8c131bbff59fb0c969217fc1d44e6d1503cd1f/rnaseq-star-align/star2pass.rnaseq_harmonization.cwl',
              'workflow_type': 'STAR - Counts',
              'workflow_version': '5d8c131bbff59fb0c969217fc1d44e6d1503cd1f'},
 'associated_entities': [{'case_id': 'cba5705a-80dd-4496-9283-c5d3a92c7dba',
                          'entity_id': 'e4f89d3b-82e2-4269-a70a-7224a9601c18',
                          'entity_submitter_id': 'TCGA-B8-4146-01B-11R-1672-07',
                          'entity_type': 'aliquot'}],
 'data_category': 'Transcriptome Profiling',
 'data_format': 'TSV',
 'data_type': 'Gene Expression Quantification',
 'experimental_strategy': 'RNA-Seq',
 'file_id': '44c858ac-1ce0-491a-aef5-979224aa09f5',
 'file_name': '144cc9bb-bd29-4986-89a7-5855168dac8e.rna_seq.augmented_star_gene_counts.tsv',
 'file_size': 4228675,
 'md5sum': 'b0f0565c1241c71c59ef841b045f2a0d',
 'platform': 'Illumina',
 'state': 'released',
 'submitter_id': '9f908caf-7eb8-4b97-80f3-96a61828c7f5'}

In [20]:
from pprint import pprint
pprint(metadata[0])

{'access': 'open',
 'analysis': {'analysis_id': 'c304e15b-cfbd-400f-881a-45f582c88a47',
              'created_datetime': '2021-12-13T19:00:47.992559-06:00',
              'input_files': [{'access': 'controlled',
                               'average_base_quality': 38,
                               'average_insert_size': 969,
                               'average_read_length': 50,
                               'created_datetime': '2021-12-13T17:59:36.019908-06:00',
                               'data_category': 'Sequencing Reads',
                               'data_format': 'BAM',
                               'data_type': 'Aligned Reads',
                               'experimental_strategy': 'RNA-Seq',
                               'file_id': '90df4ec5-31a1-4360-b24e-9b5dbe5f56e4',
                               'file_name': '144cc9bb-bd29-4986-89a7-5855168dac8e.rna_seq.genomic.gdc_realn.bam',
                               'file_size': 5597227825,
                               'md5sum': '82ac93531e3e363dafe0782f79bb1285',
                               'pairs_on_diff_chr': 254876,
                               'platform': 'Illumina',
                               'proportion_base_mismatch': 0.002437107,
                               'proportion_reads_duplicated': 0,
                               'proportion_reads_mapped': 0.9862605786849248,
                               'state': 'released',
                               'submitter_id': '242ac3e7-06fe-42ec-ba99-e9c653eba9cd',
                               'total_reads': 128680456,
                               'updated_datetime': '2023-07-12T10:44:04.997120-05:00',
                               'wgs_coverage': 'Not Applicable'}],
              'state': 'released',
              'submitter_id': '144cc9bb-bd29-4986-89a7-5855168dac8e_star__counts',
              'updated_datetime': '2022-01-19T12:49:49.189936-06:00',
              'workflow_link': 'https://github.com/NCI-GDC/gdc-rnaseq-cwl/blob/5d8c131bbff59fb0c969217fc1d44e6d1503cd1f/rnaseq-star-align/star2pass.rnaseq_harmonization.cwl',
              'workflow_type': 'STAR - Counts',
              'workflow_version': '5d8c131bbff59fb0c969217fc1d44e6d1503cd1f'},
 'associated_entities': [{'case_id': 'cba5705a-80dd-4496-9283-c5d3a92c7dba',
                          'entity_id': 'e4f89d3b-82e2-4269-a70a-7224a9601c18',
                          'entity_submitter_id': 'TCGA-B8-4146-01B-11R-1672-07',
                          'entity_type': 'aliquot'}],
 'data_category': 'Transcriptome Profiling',
 'data_format': 'TSV',
 'data_type': 'Gene Expression Quantification',
 'experimental_strategy': 'RNA-Seq',
 'file_id': '44c858ac-1ce0-491a-aef5-979224aa09f5',
 'file_name': '144cc9bb-bd29-4986-89a7-5855168dac8e.rna_seq.augmented_star_gene_counts.tsv',
 'file_size': 4228675,
 'md5sum': 'b0f0565c1241c71c59ef841b045f2a0d',
 'platform': 'Illumina',
 'state': 'released',
 'submitter_id': '9f908caf-7eb8-4b97-80f3-96a61828c7f5'}

In [21]:
metadata_rows = []

for record in metadata:

    file_id = record.get("file_id")
    file_name = record.get("file_name")
    workflow_type = record.get("analysis", {}).get("workflow_type")

    associated = record.get("associated_entities", [])

    aliquot_id = None
    aliquot_submitter_id = None
    entity_type = None

    if len(associated) > 0:
        aliquot_id = associated[0].get("entity_id")
        aliquot_submitter_id = associated[0].get("entity_submitter_id")
        entity_type = associated[0].get("entity_type")

    input_files = record.get("analysis", {}).get("input_files", [])

    total_reads = None
    proportion_reads_mapped = None
    proportion_base_mismatch = None
    average_base_quality = None
    average_read_length = None

    if len(input_files) > 0:
        inp = input_files[0]

        total_reads = inp.get("total_reads")
        proportion_reads_mapped = inp.get("proportion_reads_mapped")
        proportion_base_mismatch = inp.get("proportion_base_mismatch")
        average_base_quality = inp.get("average_base_quality")
        average_read_length = inp.get("average_read_length")

    metadata_rows.append(
        {
            "File ID": file_id,
            "File Name": file_name,
            "Aliquot ID": aliquot_id,
            "Aliquot Submitter ID": aliquot_submitter_id,
            "Entity Type": entity_type,
            "Workflow Type": workflow_type,
            "Total Reads": total_reads,
            "Proportion Reads Mapped": proportion_reads_mapped,
            "Proportion Base Mismatch": proportion_base_mismatch,
            "Average Base Quality": average_base_quality,
            "Average Read Length": average_read_length
        }
    )

metadata_table = pd.DataFrame(metadata_rows)

print("Metadata table shape:", metadata_table.shape)

display(metadata_table.head())

Metadata table shape: (542, 11)

,File ID,File Name,Aliquot ID,Aliquot Submitter ID,Entity Type,Workflow Type,Total Reads,Proportion Reads Mapped,Proportion Base Mismatch,Average Base Quality,Average Read Length
0,44c858ac-1ce0-491a-aef5-979224aa09f5,144cc9bb-bd29-4986-89a7-5855168dac8e.rna_seq.a...,e4f89d3b-82e2-4269-a70a-7224a9601c18,TCGA-B8-4146-01B-11R-1672-07,aliquot,STAR - Counts,128680456,0.986261,0.002437,38,50
1,3bca5269-8bb3-4826-bc22-e7b068853f45,44dce722-f50f-4b75-bcf4-aac9afd39e41.rna_seq.a...,19fdc607-970e-4ff5-a272-228a4a5e47de,TCGA-BP-4977-01A-01R-1334-07,aliquot,STAR - Counts,217847506,0.963624,0.003276,36,50
2,b65b4ebc-e8b9-4926-8761-56b99fbd9e9a,19f6bda2-39bb-4733-8efc-a4626afb6bd1.rna_seq.a...,5d41239a-7e24-4d75-b4e7-21eb4a48dc4d,TCGA-BP-4981-01A-01R-1334-07,aliquot,STAR - Counts,170437772,0.970376,0.003610,36,50
3,2faa29c8-49e9-4fda-baea-f73583f3a27f,11c9e0b9-c94c-466f-877a-65325a76dcaf.rna_seq.a...,7f47cd71-b62a-4f65-8479-ceec8261aaa9,TCGA-CJ-5675-01A-11R-1541-07,aliquot,STAR - Counts,169400126,0.883979,0.003237,36,50
4,633fef2c-c9ce-4b76-ae7b-0dfcc4123a6f,ba0e046d-ea06-4a64-9847-14b35eb72aee.rna_seq.a...,aed585d4-f5ff-4de3-a405-64c6c057d52e,TCGA-B0-4845-01A-01R-1277-07,aliquot,STAR - Counts,140167232,0.983567,0.002309,37,50

In [22]:
duplicate_aliquot_audit = (
    same_sample_profiles
    .merge(
        metadata_table,
        on=["File ID", "File Name"],
        how="left"
    )
    .sort_values(
        ["Case ID", "Sample ID", "Aliquot Submitter ID"]
    )
)

In [23]:
display(
    duplicate_aliquot_audit[
        [
            "Case ID",
            "Sample ID",
            "File ID",
            "Aliquot Submitter ID",
            "Total Reads",
            "Proportion Reads Mapped",
            "Proportion Base Mismatch",
            "Average Base Quality"
        ]
    ]
)

,Case ID,Sample ID,File ID,Aliquot Submitter ID,Total Reads,Proportion Reads Mapped,Proportion Base Mismatch,Average Base Quality
6,TCGA-B2-3923,TCGA-B2-3923-01A,2b393323-81e3-49e2-9acd-18eb8ab0c563,TCGA-B2-3923-01A-02R-1325-07,126664294,0.980342,0.002624,37
4,TCGA-B2-3923,TCGA-B2-3923-01A,4134fa64-6365-4a43-b990-48342be44405,TCGA-B2-3923-01A-02R-A277-07,201312044,0.913812,0.002324,37
5,TCGA-B2-3924,TCGA-B2-3924-01A,056c67e7-03b3-40cc-8c19-d6938ad634aa,TCGA-B2-3924-01A-02R-1325-07,140511116,0.985372,0.003117,37
7,TCGA-B2-3924,TCGA-B2-3924-01A,df630d23-f007-4cc4-9910-edb44046d556,TCGA-B2-3924-01A-02R-A277-07,186916242,0.594087,0.002794,37
0,TCGA-B2-5633,TCGA-B2-5633-01A,61894bd0-9fdb-4bb1-b32c-f52dbc10c850,TCGA-B2-5633-01A-01R-1541-07,120396578,0.894947,0.003927,36
3,TCGA-B2-5633,TCGA-B2-5633-01A,bdb74506-8766-42e1-922e-e03da4637a70,TCGA-B2-5633-01A-01R-A277-07,182432674,0.975191,0.002443,37
2,TCGA-B2-5635,TCGA-B2-5635-01A,b98e59fc-120a-45c4-aade-3b59ca4a1a86,TCGA-B2-5635-01A-01R-1541-07,157889094,0.886265,0.004095,36
1,TCGA-B2-5635,TCGA-B2-5635-01A,ebd01ba8-06cd-417a-b41d-05379e430fd2,TCGA-B2-5635-01A-01R-A277-07,178141180,0.967663,0.002553,37

In [24]:
multi_case_profiles = (
    duplicate_profiles
    .merge(
        metadata_table,
        on=["File ID", "File Name"],
        how="left"
    )
    .sort_values(
        ["Case ID", "Sample ID", "Aliquot Submitter ID"]
    )
)

display(
    multi_case_profiles[
        [
            "Case ID",
            "Sample ID",
            "Tumor Descriptor",
            "File ID",
            "Aliquot Submitter ID",
            "Total Reads",
            "Proportion Reads Mapped",
            "Proportion Base Mismatch",
            "Average Base Quality"
        ]
    ]
)

,Case ID,Sample ID,Tumor Descriptor,File ID,Aliquot Submitter ID,Total Reads,Proportion Reads Mapped,Proportion Base Mismatch,Average Base Quality
0,TCGA-B2-3923,TCGA-B2-3923-01A,Primary,2b393323-81e3-49e2-9acd-18eb8ab0c563,TCGA-B2-3923-01A-02R-1325-07,126664294,0.980342,0.002624,37
1,TCGA-B2-3923,TCGA-B2-3923-01A,Primary,4134fa64-6365-4a43-b990-48342be44405,TCGA-B2-3923-01A-02R-A277-07,201312044,0.913812,0.002324,37
2,TCGA-B2-3923,TCGA-B2-3923-01B,Primary,d514c3bc-c1e1-4028-9822-90ad703a3a8d,TCGA-B2-3923-01B-10R-A277-07,199691452,0.894207,0.005192,37
3,TCGA-B2-3924,TCGA-B2-3924-01A,Primary,056c67e7-03b3-40cc-8c19-d6938ad634aa,TCGA-B2-3924-01A-02R-1325-07,140511116,0.985372,0.003117,37
4,TCGA-B2-3924,TCGA-B2-3924-01A,Primary,df630d23-f007-4cc4-9910-edb44046d556,TCGA-B2-3924-01A-02R-A277-07,186916242,0.594087,0.002794,37
5,TCGA-B2-3924,TCGA-B2-3924-01B,Primary,3324e6df-28f9-42d8-8465-0fcc2d618004,TCGA-B2-3924-01B-03R-A277-07,214645858,0.914685,0.004341,37
6,TCGA-B2-5633,TCGA-B2-5633-01A,Primary,61894bd0-9fdb-4bb1-b32c-f52dbc10c850,TCGA-B2-5633-01A-01R-1541-07,120396578,0.894947,0.003927,36
7,TCGA-B2-5633,TCGA-B2-5633-01A,Primary,bdb74506-8766-42e1-922e-e03da4637a70,TCGA-B2-5633-01A-01R-A277-07,182432674,0.975191,0.002443,37
8,TCGA-B2-5633,TCGA-B2-5633-01B,Primary,307fc027-0530-452b-8fa9-d46f7fc73d0e,TCGA-B2-5633-01B-04R-A277-07,210176832,0.897727,0.004023,37
9,TCGA-B2-5635,TCGA-B2-5635-01A,Primary,b98e59fc-120a-45c4-aade-3b59ca4a1a86,TCGA-B2-5635-01A-01R-1541-07,157889094,0.886265,0.004095,36
10,TCGA-B2-5635,TCGA-B2-5635-01A,Primary,ebd01ba8-06cd-417a-b41d-05379e430fd2,TCGA-B2-5635-01A-01R-A277-07,178141180,0.967663,0.002553,37
11,TCGA-B2-5635,TCGA-B2-5635-01B,Primary,2afa2c24-7bbf-4855-acb8-feaa22dc4c33,TCGA-B2-5635-01B-04R-A277-07,213137874,0.964387,0.003911,37
12,TCGA-DV-A4W0,TCGA-DV-A4W0-01A,Primary,07b09d0e-fac2-42a7-9cac-ac1e38a92298,TCGA-DV-A4W0-01A-11R-A266-07,121358742,0.988574,0.003744,36
13,TCGA-DV-A4W0,TCGA-DV-A4W0-05A,New Primary,f8ba326c-a068-4d8c-a544-07fd13c39cbd,TCGA-DV-A4W0-05A-11R-A266-07,144369074,0.988917,0.003614,36

In [25]:
# ------------------------------------------------------------
# Define retained files for patients with multiple profiles
# ------------------------------------------------------------

preferred_file_ids = {
    "TCGA-B2-3923": "2b393323-81e3-49e2-9acd-18eb8ab0c563",
    "TCGA-B2-3924": "056c67e7-03b3-40cc-8c19-d6938ad634aa",
    "TCGA-B2-5633": "bdb74506-8766-42e1-922e-e03da4637a70",
    "TCGA-B2-5635": "ebd01ba8-06cd-417a-b41d-05379e430fd2",
    "TCGA-DV-A4W0": "07b09d0e-fac2-42a7-9cac-ac1e38a92298"
}

In [26]:
# Start with patients represented by only one RNA-seq file
single_case_ids = case_counts[case_counts == 1].index

single_profiles = sample_sheet[
    sample_sheet["Case ID"].isin(single_case_ids)
].copy()

# Select the predefined representative file
# for the five multi-profile patients
selected_multi_profiles = sample_sheet[
    sample_sheet.apply(
        lambda row:
        row["Case ID"] in preferred_file_ids
        and row["File ID"] == preferred_file_ids[row["Case ID"]],
        axis=1
    )
].copy()

# Combine into one patient-level cohort
selected_rnaseq_profiles = pd.concat(
    [single_profiles, selected_multi_profiles],
    ignore_index=True
)

selected_rnaseq_profiles = (
    selected_rnaseq_profiles
    .sort_values("Case ID")
    .reset_index(drop=True)
)

print("Selected RNA-seq profiles:", len(selected_rnaseq_profiles))
print(
    "Unique patients:",
    selected_rnaseq_profiles["Case ID"].nunique()
)
print(
    "Duplicate patients remaining:",
    selected_rnaseq_profiles["Case ID"].duplicated().sum()
)

Selected RNA-seq profiles: 533
Unique patients: 533
Duplicate patients remaining: 0

In [27]:
retained_file_ids = set(
    selected_rnaseq_profiles["File ID"]
)

excluded_profiles = sample_sheet[
    ~sample_sheet["File ID"].isin(retained_file_ids)
].copy()

print("Excluded RNA-seq profiles:", len(excluded_profiles))

display(
    excluded_profiles[
        [
            "Case ID",
            "Sample ID",
            "File ID",
            "File Name",
            "Tumor Descriptor"
        ]
    ].sort_values(["Case ID", "Sample ID"])
)

Excluded RNA-seq profiles: 9

,Case ID,Sample ID,File ID,File Name,Tumor Descriptor
96,TCGA-B2-3923,TCGA-B2-3923-01A,4134fa64-6365-4a43-b990-48342be44405,2a0d7ffd-21a2-4c9f-b420-9f78e9b8689b.rna_seq.a...,Primary
97,TCGA-B2-3923,TCGA-B2-3923-01B,d514c3bc-c1e1-4028-9822-90ad703a3a8d,d5340889-fb1c-411d-922c-a9f69e1ac405.rna_seq.a...,Primary
500,TCGA-B2-3924,TCGA-B2-3924-01A,df630d23-f007-4cc4-9910-edb44046d556,a40c1d70-1750-45d0-a85b-688331b029ea.rna_seq.a...,Primary
388,TCGA-B2-3924,TCGA-B2-3924-01B,3324e6df-28f9-42d8-8465-0fcc2d618004,f08c47f7-7b61-46a2-a961-d5fced8ebde5.rna_seq.a...,Primary
43,TCGA-B2-5633,TCGA-B2-5633-01A,61894bd0-9fdb-4bb1-b32c-f52dbc10c850,1e28caa3-197f-4deb-95c1-f6d8a41756ca.rna_seq.a...,Primary
446,TCGA-B2-5633,TCGA-B2-5633-01B,307fc027-0530-452b-8fa9-d46f7fc73d0e,9cc9f5b7-bbbb-4d3b-8d98-9bf4425a214b.rna_seq.a...,Primary
74,TCGA-B2-5635,TCGA-B2-5635-01A,b98e59fc-120a-45c4-aade-3b59ca4a1a86,c276c214-acd9-44b3-b932-971c77c4fa91.rna_seq.a...,Primary
313,TCGA-B2-5635,TCGA-B2-5635-01B,2afa2c24-7bbf-4855-acb8-feaa22dc4c33,27ea00ff-5f53-4110-9e56-8674a8e0ae40.rna_seq.a...,Primary
86,TCGA-DV-A4W0,TCGA-DV-A4W0-05A,f8ba326c-a068-4d8c-a544-07fd13c39cbd,b79c9932-bc2b-4c87-b954-3b6efd0d76e5.rna_seq.a...,New Primary

In [31]:
processed_dir = project_dir / "03_processed_data"
processed_dir.mkdir(parents=True, exist_ok=True)

In [32]:
selected_rnaseq_profiles.to_csv(
    processed_dir / "TCGA_KIRC_selected_patient_level_RNAseq_profiles.csv",
    index=False
)

excluded_profiles.to_csv(
    processed_dir / "TCGA_KIRC_excluded_duplicate_RNAseq_profiles.csv",
    index=False
)

In [33]:
multi_case_profiles.to_csv(
    processed_dir / "TCGA_KIRC_multi_profile_QC_audit.csv",
    index=False
)

In [34]:
print("Final patient-level RNA-seq cohort audit")
print("--------------------------------------")
print("Selected profiles:", len(selected_rnaseq_profiles))
print("Unique patients:", selected_rnaseq_profiles["Case ID"].nunique())
print("Duplicate patients remaining:", selected_rnaseq_profiles["Case ID"].duplicated().sum())
print("Excluded profiles:", len(excluded_profiles))

assert len(selected_rnaseq_profiles) == 533
assert selected_rnaseq_profiles["Case ID"].nunique() == 533
assert selected_rnaseq_profiles["Case ID"].duplicated().sum() == 0
assert len(excluded_profiles) == 9

print("\nAll patient-level RNA-seq audit checks passed.")

Final patient-level RNA-seq cohort audit
--------------------------------------
Selected profiles: 533
Unique patients: 533
Duplicate patients remaining: 0
Excluded profiles: 9

All patient-level RNA-seq audit checks passed.

In [35]:
from pathlib import Path
import pandas as pd
import numpy as np
import json
import requests

project_dir = Path(r"C:\Multimodal_KIRC_Project")
processed_dir = project_dir / "03_processed_data"

rnaseq_profile_path = (
    processed_dir
    / "TCGA_KIRC_selected_patient_level_RNAseq_profiles.csv"
)

selected_rnaseq = pd.read_csv(rnaseq_profile_path)

print("Final RNA-seq cohort loaded.")
print("Profiles:", len(selected_rnaseq))
print("Unique patients:", selected_rnaseq["Case ID"].nunique())

display(selected_rnaseq.head())

Final RNA-seq cohort loaded.
Profiles: 533
Unique patients: 533

,File ID,File Name,Data Category,Data Type,Project ID,Case ID,Sample ID,Tissue Type,Tumor Descriptor,Specimen Type,Preservation Method
0,21702617-18af-41b6-98fa-54395bfd0d9a,c3b9c2b0-bd3d-43ff-a17f-797122d5ac3c.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-3Z-A93Z,TCGA-3Z-A93Z-01A,Tumor,Primary,Solid Tissue,OCT
1,44dade70-3ecc-4be0-88a8-772cb763d5bb,e4497835-a45f-488e-905c-b06d578efef8.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-6D-AA2E,TCGA-6D-AA2E-01A,Tumor,Primary,Solid Tissue,OCT
2,c1215d68-5b15-44c3-9d25-73a77b0b5f31,55599384-574d-44e9-aa61-96d27b54aff1.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-A3-3306,TCGA-A3-3306-01A,Tumor,Primary,Unknown,Unknown
3,b605224a-cf9c-4092-beb4-5ed43c1179de,78855102-69a0-454f-b67a-c0919dc154fb.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-A3-3307,TCGA-A3-3307-01A,Tumor,Primary,Unknown,Unknown
4,7b34b9d4-8526-4738-87b4-f9435a1c7ae1,598575d0-6dc4-4d59-be17-5dff01e6ca52.rna_seq.a...,Transcriptome Profiling,Gene Expression Quantification,TCGA-KIRC,TCGA-A3-3308,TCGA-A3-3308-01A,Tumor,Primary,Unknown,Unknown

In [36]:
url = "https://api.gdc.cancer.gov/cases"

filters = {
    "op": "=",
    "content": {
        "field": "project.project_id",
        "value": "TCGA-KIRC"
    }
}

fields = [
    "case_id",
    "submitter_id",
    "project.project_id",
    "demographic.age_at_index",
    "demographic.gender",
    "demographic.race",
    "demographic.ethnicity",
    "demographic.vital_status",
    "demographic.days_to_death",
    "diagnoses.age_at_diagnosis",
    "diagnoses.primary_diagnosis",
    "diagnoses.tumor_grade",
    "diagnoses.ajcc_pathologic_stage",
    "diagnoses.ajcc_pathologic_t",
    "diagnoses.ajcc_pathologic_n",
    "diagnoses.ajcc_pathologic_m",
    "diagnoses.days_to_last_follow_up"
]

params = {
    "filters": json.dumps(filters),
    "fields": ",".join(fields),
    "format": "JSON",
    "size": "1000"
}

response = requests.get(url, params=params, timeout=60)

print("HTTP status:", response.status_code)

response.raise_for_status()

gdc_cases = response.json()["data"]["hits"]

print("TCGA-KIRC clinical cases retrieved:", len(gdc_cases))

HTTP status: 200
TCGA-KIRC clinical cases retrieved: 537

In [37]:
from pprint import pprint

print(gdc_cases[0].keys())
pprint(gdc_cases[0])

dict_keys(['id', 'case_id', 'project', 'submitter_id', 'diagnoses', 'demographic'])
{'case_id': 'fb9bafa5-7133-4955-8156-4eb6763dc8e1',
 'demographic': {'age_at_index': 61,
                 'ethnicity': 'not hispanic or latino',
                 'race': 'white',
                 'vital_status': 'Alive'},
 'diagnoses': [{'age_at_diagnosis': None,
                'primary_diagnosis': 'Chronic lymphocytic leukemia'},
               {'age_at_diagnosis': 22320,
                'ajcc_pathologic_m': 'M0',
                'ajcc_pathologic_n': 'N0',
                'ajcc_pathologic_stage': 'Stage I',
                'ajcc_pathologic_t': 'T1b',
                'days_to_last_follow_up': 2150.0,
                'primary_diagnosis': 'Clear cell adenocarcinoma, NOS',
                'tumor_grade': 'G2'}],
 'id': 'fb9bafa5-7133-4955-8156-4eb6763dc8e1',
 'project': {'project_id': 'TCGA-KIRC'},
 'submitter_id': 'TCGA-B0-5695'}

In [38]:
diagnosis_audit = []

for case in gdc_cases:
    diagnoses = case.get("diagnoses") or []

    diagnosis_audit.append({
        "Case ID": case.get("submitter_id"),
        "Number of Diagnoses": len(diagnoses),
        "Primary Diagnoses": [
            d.get("primary_diagnosis")
            for d in diagnoses
        ]
    })

diagnosis_audit_df = pd.DataFrame(diagnosis_audit)

print("Cases:", len(diagnosis_audit_df))
print("\nDistribution of number of diagnosis records:")
display(
    diagnosis_audit_df["Number of Diagnoses"]
    .value_counts()
    .sort_index()
    .rename_axis("Number of Diagnoses")
    .reset_index(name="Number of Cases")
)

display(
    diagnosis_audit_df[
        diagnosis_audit_df["Number of Diagnoses"] > 1
    ].head(20)
)

Cases: 537

Distribution of number of diagnosis records:

   Number of Diagnoses  Number of Cases
0                    1              338
1                    2              145
2                    3               34
3                    4               17
4                    5                2
5                    6                1

,Case ID,Number of Diagnoses,Primary Diagnoses
0,TCGA-B0-5695,2,"[Chronic lymphocytic leukemia, Clear cell aden..."
1,TCGA-BP-4807,2,"[Papillary carcinoma, follicular variant, Clea..."
2,TCGA-BP-4995,2,"[Clear cell adenocarcinoma, NOS, Not Reported]"
3,TCGA-DV-5573,4,"[Clear cell adenocarcinoma, NOS, Clear cell ca..."
5,TCGA-BP-4795,2,"[Clear cell adenocarcinoma, NOS, Papillary ade..."
6,TCGA-CZ-4862,2,"[Malignant lymphoma, non-Hodgkin, NOS, Clear c..."
7,TCGA-BP-4354,2,"[Not Reported, Clear cell adenocarcinoma, NOS]"
9,TCGA-BP-4353,2,"[Clear cell adenocarcinoma, NOS, Malignant lym..."
10,TCGA-BP-4775,2,"[Clear cell adenocarcinoma, NOS, Not Reported]"
11,TCGA-BP-4342,3,"[Clear cell adenocarcinoma, NOS, Not Reported,..."
12,TCGA-B0-5088,2,"[Malignant melanoma, NOS, Clear cell adenocarc..."
13,TCGA-B0-4712,2,"[Clear cell adenocarcinoma, NOS, Adenocarcinom..."
14,TCGA-DV-5565,3,"[Neuroendocrine carcinoma, NOS, Clear cell ade..."
15,TCGA-CJ-4869,2,"[Clear cell adenocarcinoma, NOS, Not Reported]"
16,TCGA-BP-4344,3,"[Transitional cell carcinoma, Clear cell adeno..."
17,TCGA-AK-3425,2,"[Adenocarcinoma, NOS, Clear cell adenocarcinom..."
18,TCGA-B0-4815,2,"[Pituitary adenoma, NOS, Clear cell adenocarci..."
19,TCGA-CJ-4891,2,"[Clear cell adenocarcinoma, NOS, Hodgkin lymph..."
20,TCGA-A3-3336,2,"[Clear cell adenocarcinoma, NOS, Malignant lym..."
21,TCGA-BP-4334,2,"[Not Reported, Clear cell adenocarcinoma, NOS]"

In [39]:
diagnosis_audit = []

for case in gdc_cases:
    diagnoses = case.get("diagnoses") or []

    diagnosis_audit.append({
        "Case ID": case.get("submitter_id"),
        "Number of Diagnoses": len(diagnoses),
        "Primary Diagnoses": [
            d.get("primary_diagnosis")
            for d in diagnoses
        ]
    })

diagnosis_audit_df = pd.DataFrame(diagnosis_audit)

print("Cases:", len(diagnosis_audit_df))
print("\nDistribution of number of diagnosis records:")
display(
    diagnosis_audit_df["Number of Diagnoses"]
    .value_counts()
    .sort_index()
    .rename_axis("Number of Diagnoses")
    .reset_index(name="Number of Cases")
)

display(
    diagnosis_audit_df[
        diagnosis_audit_df["Number of Diagnoses"] > 1
    ].head(20)
)

Cases: 537

Distribution of number of diagnosis records:

   Number of Diagnoses  Number of Cases
0                    1              338
1                    2              145
2                    3               34
3                    4               17
4                    5                2
5                    6                1

,Case ID,Number of Diagnoses,Primary Diagnoses
0,TCGA-B0-5695,2,"[Chronic lymphocytic leukemia, Clear cell aden..."
1,TCGA-BP-4807,2,"[Papillary carcinoma, follicular variant, Clea..."
2,TCGA-BP-4995,2,"[Clear cell adenocarcinoma, NOS, Not Reported]"
3,TCGA-DV-5573,4,"[Clear cell adenocarcinoma, NOS, Clear cell ca..."
5,TCGA-BP-4795,2,"[Clear cell adenocarcinoma, NOS, Papillary ade..."
6,TCGA-CZ-4862,2,"[Malignant lymphoma, non-Hodgkin, NOS, Clear c..."
7,TCGA-BP-4354,2,"[Not Reported, Clear cell adenocarcinoma, NOS]"
9,TCGA-BP-4353,2,"[Clear cell adenocarcinoma, NOS, Malignant lym..."
10,TCGA-BP-4775,2,"[Clear cell adenocarcinoma, NOS, Not Reported]"
11,TCGA-BP-4342,3,"[Clear cell adenocarcinoma, NOS, Not Reported,..."
12,TCGA-B0-5088,2,"[Malignant melanoma, NOS, Clear cell adenocarc..."
13,TCGA-B0-4712,2,"[Clear cell adenocarcinoma, NOS, Adenocarcinom..."
14,TCGA-DV-5565,3,"[Neuroendocrine carcinoma, NOS, Clear cell ade..."
15,TCGA-CJ-4869,2,"[Clear cell adenocarcinoma, NOS, Not Reported]"
16,TCGA-BP-4344,3,"[Transitional cell carcinoma, Clear cell adeno..."
17,TCGA-AK-3425,2,"[Adenocarcinoma, NOS, Clear cell adenocarcinom..."
18,TCGA-B0-4815,2,"[Pituitary adenoma, NOS, Clear cell adenocarci..."
19,TCGA-CJ-4891,2,"[Clear cell adenocarcinoma, NOS, Hodgkin lymph..."
20,TCGA-A3-3336,2,"[Clear cell adenocarcinoma, NOS, Malignant lym..."
21,TCGA-BP-4334,2,"[Not Reported, Clear cell adenocarcinoma, NOS]"

In [40]:
all_diagnoses = []

for case in gdc_cases:
    for diagnosis in case.get("diagnoses") or []:
        all_diagnoses.append({
            "Case ID": case.get("submitter_id"),
            "Primary Diagnosis": diagnosis.get("primary_diagnosis"),
            "AJCC Stage": diagnosis.get("ajcc_pathologic_stage"),
            "AJCC T": diagnosis.get("ajcc_pathologic_t"),
            "AJCC N": diagnosis.get("ajcc_pathologic_n"),
            "AJCC M": diagnosis.get("ajcc_pathologic_m"),
            "Tumor Grade": diagnosis.get("tumor_grade"),
            "Age at Diagnosis": diagnosis.get("age_at_diagnosis"),
            "Days to Last Follow-up": diagnosis.get("days_to_last_follow_up")
        })

all_diagnoses_df = pd.DataFrame(all_diagnoses)

display(
    all_diagnoses_df["Primary Diagnosis"]
    .value_counts(dropna=False)
    .reset_index()
    .rename(columns={
        "Primary Diagnosis": "Number of Records",
        "index": "Primary Diagnosis"
    })
)

                              Number of Records  count
0                Clear cell adenocarcinoma, NOS    576
1                                  Not Reported    149
2                           Adenocarcinoma, NOS     16
3                          Clear cell carcinoma     15
4                     Renal cell carcinoma, NOS     14
5                  Squamous cell carcinoma, NOS      5
6                 Neuroendocrine carcinoma, NOS      4
7          Malignant lymphoma, non-Hodgkin, NOS      3
8                   Transitional cell carcinoma      3
9                                 Melanoma, NOS      3
10                 Chronic lymphocytic leukemia      2
11                     Follicular lymphoma, NOS      2
12               Papillary renal cell carcinoma      2
13                         Carcinoid tumor, NOS      2
14      Papillary carcinoma, follicular variant      1
15                Papillary adenocarcinoma, NOS      1
16                      Malignant lymphoma, NOS      1
17                      Malignant melanoma, NOS      1
18                       Pituitary adenoma, NOS      1
19                        Hodgkin lymphoma, NOS      1
20                      Mucinous adenocarcinoma      1
21                              Hemangioma, NOS      1
22                          Hairy cell leukemia      1
23                     Papillary carcinoma, NOS      1
24             Basaloid squamous cell carcinoma      1
25  Intraductal carcinoma, noninfiltrating, NOS      1
26                Basal cell carcinoma, nodular      1
27                Ductal carcinoma in situ, NOS      1
28                Combined small cell carcinoma      1
29                      Adenosquamous carcinoma      1
30     Squamous cell carcinoma, clear cell type      1
31                     Papillary microcarcinoma      1

In [41]:
def select_kirc_diagnosis(diagnoses):
    if not diagnoses:
        return {}

    # Prefer the renal clear-cell carcinoma record
    clear_cell = [
        d for d in diagnoses
        if "clear cell" in str(
            d.get("primary_diagnosis", "")
        ).lower()
    ]

    if clear_cell:
        # If more than one clear-cell record exists,
        # prefer one containing pathologic stage information
        staged = [
            d for d in clear_cell
            if d.get("ajcc_pathologic_stage") is not None
        ]

        if staged:
            return staged[0]

        return clear_cell[0]

    # Fallback only when no clear-cell diagnosis is available
    return diagnoses[0]

In [42]:
clinical_rows = []

for case in gdc_cases:

    demographic = case.get("demographic") or {}
    diagnoses = case.get("diagnoses") or []

    diagnosis = select_kirc_diagnosis(diagnoses)

    clinical_rows.append({
        "Case ID": case.get("submitter_id"),
        "GDC Case UUID": case.get("case_id"),

        "Age at Index": demographic.get("age_at_index"),
        "Gender": demographic.get("gender"),
        "Race": demographic.get("race"),
        "Ethnicity": demographic.get("ethnicity"),
        "Vital Status": demographic.get("vital_status"),
        "Days to Death": demographic.get("days_to_death"),

        "Age at Diagnosis Days":
            diagnosis.get("age_at_diagnosis"),

        "Primary Diagnosis":
            diagnosis.get("primary_diagnosis"),

        "Tumor Grade":
            diagnosis.get("tumor_grade"),

        "AJCC Stage":
            diagnosis.get("ajcc_pathologic_stage"),

        "AJCC T":
            diagnosis.get("ajcc_pathologic_t"),

        "AJCC N":
            diagnosis.get("ajcc_pathologic_n"),

        "AJCC M":
            diagnosis.get("ajcc_pathologic_m"),

        "Days to Last Follow-up":
            diagnosis.get("days_to_last_follow_up"),

        "Number of Diagnosis Records":
            len(diagnoses)
    })

clinical_df = pd.DataFrame(clinical_rows)

print("Clinical table shape:", clinical_df.shape)
print("Unique clinical patients:", clinical_df["Case ID"].nunique())

display(clinical_df.head())

Clinical table shape: (537, 17)
Unique clinical patients: 537

,Case ID,GDC Case UUID,Age at Index,Gender,Race,Ethnicity,Vital Status,Days to Death,Age at Diagnosis Days,Primary Diagnosis,Tumor Grade,AJCC Stage,AJCC T,AJCC N,AJCC M,Days to Last Follow-up,Number of Diagnosis Records
0,TCGA-B0-5695,fb9bafa5-7133-4955-8156-4eb6763dc8e1,61,None,white,not hispanic or latino,Alive,NaN,22320.0,"Clear cell adenocarcinoma, NOS",G2,Stage I,T1b,N0,M0,2150.0,2
1,TCGA-BP-4807,33cf0893-0411-4758-aa90-602bfedf0850,42,None,white,not reported,Alive,NaN,15360.0,"Clear cell adenocarcinoma, NOS",G3,Stage I,T1a,NX,M0,211.0,2
2,TCGA-BP-4995,9245a557-01ea-4446-b9e9-313f6ab18834,68,None,white,not hispanic or latino,Alive,NaN,24850.0,"Clear cell adenocarcinoma, NOS",G3,Stage I,T1b,N0,M0,1371.0,2
3,TCGA-DV-5573,c6454371-1f84-4e8e-8c3a-2eac8380819e,41,None,white,not hispanic or latino,Alive,NaN,15264.0,"Clear cell adenocarcinoma, NOS",G2,Stage I,T1a,NX,M0,1130.0,4
4,TCGA-CJ-4900,33cd8b05-2b9b-40dd-97a2-40d02e27ee90,69,None,white,not hispanic or latino,Dead,1714.0,25508.0,"Clear cell adenocarcinoma, NOS",G4,Stage IV,T4,N1,M1,1714.0,1

In [43]:
display(
    clinical_df["Primary Diagnosis"]
    .value_counts(dropna=False)
    .reset_index()
)

                Primary Diagnosis  count
0  Clear cell adenocarcinoma, NOS    518
1       Renal cell carcinoma, NOS     13
2            Clear cell carcinoma      5
3                    Not Reported      1

In [44]:
rnaseq_patient_ids = set(
    selected_rnaseq["Case ID"]
)

clinical_matched = clinical_df[
    clinical_df["Case ID"].isin(rnaseq_patient_ids)
].copy()

missing_clinical_ids = sorted(
    rnaseq_patient_ids
    - set(clinical_matched["Case ID"])
)

print("RNA-seq patients:", len(rnaseq_patient_ids))
print(
    "RNA-seq patients with clinical records:",
    clinical_matched["Case ID"].nunique()
)
print(
    "RNA-seq patients without clinical records:",
    len(missing_clinical_ids)
)

if missing_clinical_ids:
    print(missing_clinical_ids)

RNA-seq patients: 533
RNA-seq patients with clinical records: 533
RNA-seq patients without clinical records: 0

In [45]:
clinical_variables = [
    "Age at Index",
    "Gender",
    "Race",
    "Ethnicity",
    "Vital Status",
    "Days to Death",
    "Age at Diagnosis Days",
    "Primary Diagnosis",
    "Tumor Grade",
    "AJCC Stage",
    "AJCC T",
    "AJCC N",
    "AJCC M",
    "Days to Last Follow-up"
]

clinical_missingness = pd.DataFrame({
    "Variable": clinical_variables,
    "Available N": [
        clinical_matched[col].notna().sum()
        for col in clinical_variables
    ],
    "Missing N": [
        clinical_matched[col].isna().sum()
        for col in clinical_variables
    ],
    "Missing %": [
        100 * clinical_matched[col].isna().mean()
        for col in clinical_variables
    ]
})

clinical_missingness["Missing %"] = (
    clinical_missingness["Missing %"].round(2)
)

display(clinical_missingness)

                  Variable  Available N  Missing N  Missing %
0             Age at Index          533          0       0.00
1                   Gender            0        533     100.00
2                     Race          533          0       0.00
3                Ethnicity          533          0       0.00
4             Vital Status          533          0       0.00
5            Days to Death          175        358      67.17
6    Age at Diagnosis Days          527          6       1.13
7        Primary Diagnosis          533          0       0.00
8              Tumor Grade          523         10       1.88
9               AJCC Stage          530          3       0.56
10                  AJCC T          533          0       0.00
11                  AJCC N          533          0       0.00
12                  AJCC M          531          2       0.38
13  Days to Last Follow-up          526          7       1.31

In [46]:
for col in [
    "Gender",
    "Vital Status",
    "Tumor Grade",
    "AJCC Stage",
    "AJCC T",
    "AJCC N",
    "AJCC M"
]:
    print(f"\n--- {col} ---")
    display(
        clinical_matched[col]
        .value_counts(dropna=False)
        .rename_axis(col)
        .reset_index(name="N")
    )

--- Gender ---

  Gender    N
0   None  533

--- Vital Status ---

  Vital Status    N
0        Alive  358
1         Dead  175

--- Tumor Grade ---

  Tumor Grade    N
0          G2  226
1          G3  204
2          G4   75
3          G1   13
4         NaN   10
5          GX    5

--- AJCC Stage ---

  AJCC Stage    N
0    Stage I  267
1  Stage III  122
2   Stage IV   83
3   Stage II   57
4        NaN    3
5   Stage IB    1

--- AJCC T ---

   AJCC T    N
0     T1a  141
1     T3a  120
2     T1b  110
3      T2   55
4     T3b   52
5      T1   23
6      T4   11
7     T2a   10
8      T3    5
9     T2b    4
10    T3c    2

--- AJCC N ---

  AJCC N    N
0     NX  275
1     N0  242
2     N1   16

--- AJCC M ---

  AJCC M    N
0     M0  419
1     M1   79
2     MX   33
3    NaN    2

In [47]:
clinical_raw_dir = project_dir / "01_raw_downloads" / "clinical"

cdr_path = (
    clinical_raw_dir
    / "TCGA-CDR-SupplementalTableS1.xlsx"
)

cdr = pd.read_excel(cdr_path)

print("TCGA-CDR shape:", cdr.shape)
print("Columns:")
print(cdr.columns.tolist())

display(cdr.head())

TCGA-CDR shape: (11160, 34)
Columns:
['Unnamed: 0', 'bcr_patient_barcode', 'type', 'age_at_initial_pathologic_diagnosis', 'gender', 'race', 'ajcc_pathologic_tumor_stage', 'clinical_stage', 'histological_type', 'histological_grade', 'initial_pathologic_dx_year', 'menopause_status', 'birth_days_to', 'vital_status', 'tumor_status', 'last_contact_days_to', 'death_days_to', 'cause_of_death', 'new_tumor_event_type', 'new_tumor_event_site', 'new_tumor_event_site_other', 'new_tumor_event_dx_days_to', 'treatment_outcome_first_course', 'margin_status', 'residual_tumor', 'OS', 'OS.time', 'DSS', 'DSS.time', 'DFI', 'DFI.time', 'PFI', 'PFI.time', 'Redaction']

,Unnamed: 0,bcr_patient_barcode,type,age_at_initial_pathologic_diagnosis,gender,race,ajcc_pathologic_tumor_stage,clinical_stage,histological_type,histological_grade,...,residual_tumor,OS,OS.time,DSS,DSS.time,DFI,DFI.time,PFI,PFI.time,Redaction
0,1,TCGA-OR-A5J1,ACC,58.0,MALE,WHITE,Stage II,[Not Applicable],Adrenocortical carcinoma- Usual Type,[Not Available],...,NaN,1.0,1355.0,1.0,1355.0,1.0,754.0,1.0,754.0,NaN
1,2,TCGA-OR-A5J2,ACC,44.0,FEMALE,WHITE,Stage IV,[Not Applicable],Adrenocortical carcinoma- Usual Type,[Not Available],...,NaN,1.0,1677.0,1.0,1677.0,NaN,NaN,1.0,289.0,NaN
2,3,TCGA-OR-A5J3,ACC,23.0,FEMALE,WHITE,Stage III,[Not Applicable],Adrenocortical carcinoma- Usual Type,[Not Available],...,NaN,0.0,2091.0,0.0,2091.0,1.0,53.0,1.0,53.0,NaN
3,4,TCGA-OR-A5J4,ACC,23.0,FEMALE,WHITE,Stage IV,[Not Applicable],Adrenocortical carcinoma- Usual Type,[Not Available],...,NaN,1.0,423.0,1.0,423.0,NaN,NaN,1.0,126.0,NaN
4,5,TCGA-OR-A5J5,ACC,30.0,MALE,WHITE,Stage III,[Not Applicable],Adrenocortical carcinoma- Usual Type,[Not Available],...,NaN,1.0,365.0,1.0,365.0,NaN,NaN,1.0,50.0,NaN

In [48]:
# Extract TCGA-KIRC patients from the curated TCGA-CDR resource

kirc_cdr = cdr[
    cdr["type"].astype(str).str.upper().eq("KIRC")
].copy()

print("KIRC patients in TCGA-CDR:", len(kirc_cdr))
print("Unique KIRC patient barcodes:", kirc_cdr["bcr_patient_barcode"].nunique())

display(
    kirc_cdr[
        [
            "bcr_patient_barcode",
            "type",
            "OS",
            "OS.time",
            "DSS",
            "DSS.time",
            "DFI",
            "DFI.time",
            "PFI",
            "PFI.time"
        ]
    ].head(10)
)

KIRC patients in TCGA-CDR: 537
Unique KIRC patient barcodes: 537

,bcr_patient_barcode,type,OS,OS.time,DSS,DSS.time,DFI,DFI.time,PFI,PFI.time
3882,TCGA-3Z-A93Z,KIRC,0.0,385.0,0.0,385.0,0.0,385.0,0.0,385.0
3883,TCGA-6D-AA2E,KIRC,0.0,362.0,0.0,362.0,NaN,NaN,0.0,362.0
3884,TCGA-A3-3306,KIRC,0.0,1120.0,0.0,1120.0,NaN,NaN,0.0,1120.0
3885,TCGA-A3-3307,KIRC,0.0,1436.0,0.0,1436.0,NaN,NaN,0.0,1436.0
3886,TCGA-A3-3308,KIRC,0.0,16.0,0.0,16.0,NaN,NaN,0.0,16.0
3887,TCGA-A3-3311,KIRC,1.0,1191.0,0.0,1191.0,NaN,NaN,0.0,1191.0
3888,TCGA-A3-3313,KIRC,1.0,735.0,0.0,735.0,NaN,NaN,0.0,735.0
3889,TCGA-A3-3316,KIRC,0.0,1493.0,0.0,1493.0,NaN,NaN,0.0,1493.0
3890,TCGA-A3-3317,KIRC,0.0,1491.0,0.0,1491.0,NaN,NaN,1.0,560.0
3891,TCGA-A3-3319,KIRC,0.0,1130.0,0.0,1130.0,NaN,NaN,0.0,1130.0

In [49]:
kirc_cdr = kirc_cdr.rename(
    columns={"bcr_patient_barcode": "Case ID"}
)

survival_matched = (
    selected_rnaseq[["Case ID"]]
    .merge(
        kirc_cdr,
        on="Case ID",
        how="left"
    )
)

print("RNA-seq patients:", len(selected_rnaseq))
print("Matched survival rows:", len(survival_matched))
print("Unique matched patients:", survival_matched["Case ID"].nunique())

RNA-seq patients: 533
Matched survival rows: 533
Unique matched patients: 533

In [50]:
survival_endpoint_audit = pd.DataFrame({
    "Endpoint": ["OS", "DSS", "DFI", "PFI"],
    "Event Available N": [
        survival_matched["OS"].notna().sum(),
        survival_matched["DSS"].notna().sum(),
        survival_matched["DFI"].notna().sum(),
        survival_matched["PFI"].notna().sum()
    ],
    "Time Available N": [
        survival_matched["OS.time"].notna().sum(),
        survival_matched["DSS.time"].notna().sum(),
        survival_matched["DFI.time"].notna().sum(),
        survival_matched["PFI.time"].notna().sum()
    ]
})

survival_endpoint_audit["Complete Endpoint N"] = [
    survival_matched[["OS", "OS.time"]].dropna().shape[0],
    survival_matched[["DSS", "DSS.time"]].dropna().shape[0],
    survival_matched[["DFI", "DFI.time"]].dropna().shape[0],
    survival_matched[["PFI", "PFI.time"]].dropna().shape[0]
]

display(survival_endpoint_audit)

  Endpoint  Event Available N  Time Available N  Complete Endpoint N
0       OS                533               533                  533
1      DSS                522               533                  522
2      DFI                117               117                  117
3      PFI                533               531                  531

In [51]:
for endpoint in ["OS", "DSS", "DFI", "PFI"]:
    print(f"\n--- {endpoint} ---")
    display(
        survival_matched[endpoint]
        .value_counts(dropna=False)
        .sort_index()
        .rename_axis(endpoint)
        .reset_index(name="N")
    )

--- OS ---

    OS    N
0  0.0  358
1  1.0  175

--- DSS ---

   DSS    N
0  0.0  413
1  1.0  109
2  NaN   11

--- DFI ---

   DFI    N
0  0.0  102
1  1.0   15
2  NaN  416

--- PFI ---

   PFI    N
0  0.0  372
1  1.0  161

In [52]:
# ------------------------------------------------------------
# Build survival endpoint datasets
# ------------------------------------------------------------

pfi_cohort = survival_matched[
    survival_matched["PFI"].notna()
    & survival_matched["PFI.time"].notna()
].copy()

os_cohort = survival_matched[
    survival_matched["OS"].notna()
    & survival_matched["OS.time"].notna()
].copy()

print("PFI cohort")
print("-----------")
print("Patients:", len(pfi_cohort))
print("Events:", int(pfi_cohort["PFI"].sum()))
print("Censored:", int((pfi_cohort["PFI"] == 0).sum()))
print("Minimum follow-up time:", pfi_cohort["PFI.time"].min())
print("Median follow-up/event time:", pfi_cohort["PFI.time"].median())
print("Maximum follow-up time:", pfi_cohort["PFI.time"].max())

print("\nOS cohort")
print("---------")
print("Patients:", len(os_cohort))
print("Deaths:", int(os_cohort["OS"].sum()))
print("Censored:", int((os_cohort["OS"] == 0).sum()))
print("Minimum follow-up time:", os_cohort["OS.time"].min())
print("Median follow-up/event time:", os_cohort["OS.time"].median())
print("Maximum follow-up time:", os_cohort["OS.time"].max())

PFI cohort
-----------
Patients: 531
Events: 159
Censored: 372
Minimum follow-up time: 0.0
Median follow-up/event time: 1011.0
Maximum follow-up time: 4074.0

OS cohort
---------
Patients: 533
Deaths: 175
Censored: 358
Minimum follow-up time: 0.0
Median follow-up/event time: 1191.0
Maximum follow-up time: 4537.0

In [53]:
print(
    "PFI times <= 0:",
    (pfi_cohort["PFI.time"] <= 0).sum()
)

print(
    "OS times <= 0:",
    (os_cohort["OS.time"] <= 0).sum()
)

PFI times <= 0: 2
OS times <= 0: 2

In [54]:
clinical_survival = (
    clinical_matched
    .merge(
        survival_matched[
            [
                "Case ID",
                "OS",
                "OS.time",
                "PFI",
                "PFI.time",
                "DSS",
                "DSS.time"
            ]
        ],
        on="Case ID",
        how="left"
    )
)

print("Clinical-survival rows:", len(clinical_survival))
print(
    "Unique patients:",
    clinical_survival["Case ID"].nunique()
)

display(clinical_survival.head())

Clinical-survival rows: 533
Unique patients: 533

,Case ID,GDC Case UUID,Age at Index,Gender,Race,Ethnicity,Vital Status,Days to Death,Age at Diagnosis Days,Primary Diagnosis,...,AJCC N,AJCC M,Days to Last Follow-up,Number of Diagnosis Records,OS,OS.time,PFI,PFI.time,DSS,DSS.time
0,TCGA-B0-5695,fb9bafa5-7133-4955-8156-4eb6763dc8e1,61,None,white,not hispanic or latino,Alive,NaN,22320.0,"Clear cell adenocarcinoma, NOS",...,N0,M0,2150.0,2,0.0,2150.0,0.0,2150.0,0.0,2150.0
1,TCGA-BP-4807,33cf0893-0411-4758-aa90-602bfedf0850,42,None,white,not reported,Alive,NaN,15360.0,"Clear cell adenocarcinoma, NOS",...,NX,M0,211.0,2,0.0,211.0,0.0,211.0,0.0,211.0
2,TCGA-BP-4995,9245a557-01ea-4446-b9e9-313f6ab18834,68,None,white,not hispanic or latino,Alive,NaN,24850.0,"Clear cell adenocarcinoma, NOS",...,N0,M0,1371.0,2,0.0,1371.0,0.0,1371.0,0.0,1371.0
3,TCGA-DV-5573,c6454371-1f84-4e8e-8c3a-2eac8380819e,41,None,white,not hispanic or latino,Alive,NaN,15264.0,"Clear cell adenocarcinoma, NOS",...,NX,M0,1130.0,4,0.0,1130.0,0.0,1130.0,0.0,1130.0
4,TCGA-CJ-4900,33cd8b05-2b9b-40dd-97a2-40d02e27ee90,69,None,white,not hispanic or latino,Dead,1714.0,25508.0,"Clear cell adenocarcinoma, NOS",...,N1,M1,1714.0,1,1.0,1714.0,1.0,1714.0,1.0,1714.0

In [56]:
clinical_survival.to_csv(
    processed_dir / "TCGA_KIRC_clinical_survival_harmonized.csv",
    index=False
)

survival_endpoint_audit.to_csv(
    processed_dir / "TCGA_KIRC_survival_endpoint_audit.csv",
    index=False
)

In [57]:
pfi_missing_time = survival_matched[
    survival_matched["PFI"].notna()
    & survival_matched["PFI.time"].isna()
].copy()

print("Patients with PFI status but missing PFI time:", len(pfi_missing_time))

display(
    pfi_missing_time[
        [
            "Case ID",
            "PFI",
            "PFI.time",
            "OS",
            "OS.time",
            "DSS",
            "DSS.time"
        ]
    ]
)

Patients with PFI status but missing PFI time: 2

          Case ID  PFI  PFI.time   OS  OS.time  DSS  DSS.time
380  TCGA-BP-5201  1.0       NaN  0.0    951.0  0.0     951.0
389  TCGA-CJ-4641  1.0       NaN  1.0   1661.0  1.0    1661.0

In [58]:
zero_time_audit = survival_matched[
    (survival_matched["PFI.time"] <= 0)
    | (survival_matched["OS.time"] <= 0)
].copy()

display(
    zero_time_audit[
        [
            "Case ID",
            "PFI",
            "PFI.time",
            "OS",
            "OS.time",
            "DSS",
            "DSS.time"
        ]
    ]
)

         Case ID  PFI  PFI.time   OS  OS.time  DSS  DSS.time
49  TCGA-A3-A8OU  0.0       0.0  0.0      0.0  0.0       0.0
52  TCGA-A3-A8OX  0.0       0.0  0.0      0.0  0.0       0.0

In [59]:
zero_time_clinical = (
    zero_time_audit[
        [
            "Case ID",
            "PFI",
            "PFI.time",
            "OS",
            "OS.time"
        ]
    ]
    .merge(
        clinical_matched[
            [
                "Case ID",
                "Vital Status",
                "Days to Death",
                "Days to Last Follow-up",
                "AJCC Stage",
                "Tumor Grade"
            ]
        ],
        on="Case ID",
        how="left"
    )
)

display(zero_time_clinical)

,Case ID,PFI,PFI.time,OS,OS.time,Vital Status,Days to Death,Days to Last Follow-up,AJCC Stage,Tumor Grade
0,TCGA-A3-A8OU,0.0,0.0,0.0,0.0,Alive,NaN,0.0,Stage I,G1
1,TCGA-A3-A8OX,0.0,0.0,0.0,0.0,Alive,NaN,0.0,Stage I,G3

In [60]:
print("PFI zero-time records:")
display(
    survival_matched.loc[
        survival_matched["PFI.time"] == 0,
        ["Case ID", "PFI", "PFI.time"]
    ]
)

print("\nOS zero-time records:")
display(
    survival_matched.loc[
        survival_matched["OS.time"] == 0,
        ["Case ID", "OS", "OS.time"]
    ]
)

PFI zero-time records:

         Case ID  PFI  PFI.time
49  TCGA-A3-A8OU  0.0       0.0
52  TCGA-A3-A8OX  0.0       0.0

OS zero-time records:

         Case ID   OS  OS.time
49  TCGA-A3-A8OU  0.0      0.0
52  TCGA-A3-A8OX  0.0      0.0

In [62]:
# ============================================================
# FINAL SURVIVAL ELIGIBILITY RULE
# Require:
#   1. nonmissing event indicator
#   2. nonmissing survival time
#   3. strictly positive survival time
# ============================================================

pfi_final = survival_matched[
    survival_matched["PFI"].notna()
    & survival_matched["PFI.time"].notna()
    & (survival_matched["PFI.time"] > 0)
].copy()

os_final = survival_matched[
    survival_matched["OS"].notna()
    & survival_matched["OS.time"].notna()
    & (survival_matched["OS.time"] > 0)
].copy()

print("FINAL PFI COHORT")
print("----------------")
print("Patients:", len(pfi_final))
print("Events:", int(pfi_final["PFI"].sum()))
print("Censored:", int((pfi_final["PFI"] == 0).sum()))
print("Minimum time:", pfi_final["PFI.time"].min())
print("Median time:", pfi_final["PFI.time"].median())
print("Maximum time:", pfi_final["PFI.time"].max())

print("\nFINAL OS COHORT")
print("---------------")
print("Patients:", len(os_final))
print("Deaths:", int(os_final["OS"].sum()))
print("Censored:", int((os_final["OS"] == 0).sum()))
print("Minimum time:", os_final["OS.time"].min())
print("Median time:", os_final["OS.time"].median())
print("Maximum time:", os_final["OS.time"].max())

FINAL PFI COHORT
----------------
Patients: 529
Events: 159
Censored: 370
Minimum time: 2.0
Median time: 1014.0
Maximum time: 4074.0

FINAL OS COHORT
---------------
Patients: 531
Deaths: 175
Censored: 356
Minimum time: 2.0
Median time: 1200.0
Maximum time: 4537.0

In [63]:
assert len(pfi_final) == 529
assert int(pfi_final["PFI"].sum()) == 159
assert (pfi_final["PFI.time"] > 0).all()

assert len(os_final) == 531
assert int(os_final["OS"].sum()) == 175
assert (os_final["OS.time"] > 0).all()

print("All final survival eligibility checks passed.")

All final survival eligibility checks passed.

In [64]:
survival_exclusion_audit = pd.DataFrame([
    {
        "Case ID": "TCGA-BP-5201",
        "Endpoint": "PFI",
        "Reason": "PFI event recorded but PFI.time missing"
    },
    {
        "Case ID": "TCGA-CJ-4641",
        "Endpoint": "PFI",
        "Reason": "PFI event recorded but PFI.time missing"
    },
    {
        "Case ID": "TCGA-A3-A8OU",
        "Endpoint": "PFI and OS",
        "Reason": "Zero follow-up time; censored at day 0"
    },
    {
        "Case ID": "TCGA-A3-A8OX",
        "Endpoint": "PFI and OS",
        "Reason": "Zero follow-up time; censored at day 0"
    }
])

display(survival_exclusion_audit)

        Case ID    Endpoint                                   Reason
0  TCGA-BP-5201         PFI  PFI event recorded but PFI.time missing
1  TCGA-CJ-4641         PFI  PFI event recorded but PFI.time missing
2  TCGA-A3-A8OU  PFI and OS   Zero follow-up time; censored at day 0
3  TCGA-A3-A8OX  PFI and OS   Zero follow-up time; censored at day 0

In [65]:
survival_exclusion_audit.to_csv(
    processed_dir / "TCGA_KIRC_survival_exclusion_audit.csv",
    index=False
)

In [67]:
pfi_final.to_csv(
    processed_dir / "TCGA_KIRC_final_PFI_cohort.csv",
    index=False
)

os_final.to_csv(
    processed_dir / "TCGA_KIRC_final_OS_cohort.csv",
    index=False
)

clinical_survival.to_csv(
    processed_dir / "TCGA_KIRC_clinical_survival_harmonized.csv",
    index=False
)